window.TERM_ICONS={
'Fleisch.html':'🐄 🐖 🐔 🦃 🐑 🌭 🥓 🍖 🍗 🥩 🐟 🐟 🐟 🐟 🦐 🦀 🦪 🦑'.split(' '),
'Getraenke.html':'💧 💦 🧃 🍊 🍋 🥤 🥛 ☕ ☕ ☕ 🫖 🍫 🍺 🍷 🍷 🥂 🍾 🥤'.split(' '),
'Restaurant.html':'🍽️ 🪑 📋 🍷 🧑‍🍳 👩‍🍳 📝 💡 🥗 🍲 🍚 🍰 🥬 😋 🧾 💳 💶 📅'.split(' '),
'Geschirr.html':'🍽️ ☕ 🥛 🥣 🍴 🔪 🥄 🥄 🍲 🍳 🫙 🪵 ♨️ 🔥 🧑‍🍳 🍳 🥧 🔪'.split(' '),
'Gewuerze.html':'🧂 🌶️ 🍬 🌾 🫗 🍶 🧈 🥛 🥚 🧄 🧅 🫚 🌿 🌿 🫙 🧂 🥫 🥕'.split(' '),
'Wohnung.html':'🏢 🏠 🚪 🛋️ 🛏️ 🧸 🍳 🛁 🚪 🌇 🧱 🏚️ 🚪 🪟 🧱 🪵 🪜 🌳'.split(' '),
'Haushalt.html':'✨ 🧺 🧹 🧽 🍽️ 🫧 ♨️ 🧹 🧹 🪣 🧽 🧽 🧴 🗑️ 🗑️ 🧺 🧹 ✨'.split(' '),
'Elektro.html':'🧊 🫧 🍽️ ♨️ 🔥 📻 🫖 ☕ 🍞 🧹 ♨️ 📺 💡 💨 🔌 🔌 🔛 ⏹️'.split(' '),
'Wohnungssuche.html':'📰 👀 🔑 🔑 🧑 💶 🧾 🧾 🧾 💰 📄 📐 🛋️ 📍 🤫 ✅ 📦 📨'.split(' '),
'Kleidung.html':'👕 👔 👚 🧶 🧥 🧥 👖 👖 👗 👗 🤵 🩲 🛌 🧦 🪢 👔 👕 🧥'.split(' '),
'Schuhe.html':'👟 👟 🥾 👡 🥿 👠 👜 🎒 👜 🎩 🧢 🧣 🧤 👓 🕶️ ⌚ 💎 📿'.split(' '),
'Koerper.html':'🙂 😀 💇 👁️ 👂 👃 👄 🦷 🧣 🤷 💪 ✋ ☝️ 🫃 🔙 🦵 🦿 🦶'.split(' '),
'Arzt.html':'👨‍⚕️ 👩‍⚕️ 🤒 🏥 📅 🦠 🤕 🌡️ 😷 🤧 🤒 💊 💊 📃 🩺 🤕 🤒 💚'.split(' '),
'Koerperpflege.html':'🧼 🧴 🧴 🪥 🦷 🧻 🪮 🪮 🪒 🧴 🌸 🌸 💄 💄 🪞 🚿 🫧 🪒'.split(' '),
'Fahrzeuge.html':'🚗 🚌 🚋 🚇 🚆 🚆 🚲 🏍️ 🚚 🚕 ✈️ 🚢 ⛴️ 🛴 🚘 ⬆️ ⬇️ 🔄'.split(' '),
'Bahnhof.html':'🚉 🛫 🛤️ 🛤️ 🚏 🎫 🗓️ 🛫 🛬 ⏳ 🪟 🧳 🧳 🛂 🎟️ ✅ 🚆 🛬'.split(' '),
'Stadt.html':'🏙️ 🌆 🛣️ 🏛️ 🌳 🏛️ 📚 🏺 🎭 🎬 ⚕️ 🏥 🏦 📮 👮 ⛪ 🛒 🚶'.split(' '),
'Weg.html':'🛣️ 🧭 ⬅️ ➡️ ⬆️ 📍 👉 ⏩ ⏪ ↔️ ↪️ ↔️ ↩️ ✚ 🚦 ↪️ 🚶 🗺️'.split(' '),
'Reise.html':'🧳 🏖️ 📍 🏨 🛏️ 🛏️ 🛎️ 🔑 🌙 🥐 📅 📝 ❌ 🛌 🗺️ 🏛️ 🥾 🛌'.split(' '),
'Supermarkt.html':'🛒 🛒 🧺 🗄️ 💳 🧾 🏷️ 📦 🍾 🥫 🫙 🧩 ⚖️ ⚖️ ⚖️ 🛒'.split(' '),
'Kleidung-kaufen.html':'🏬 🚪 📏 🎨 🏷️ 🏷️ 🏷️ 👕 👌 👌 ↔️ ↔️ ↕️ 🔄 ↩️ 🧾'.split(' '),
'Geld.html':'💶 🪙 🪙 💵 🪙 💶 💳 💳 🏦 🏧 💳 🏷️ 💵 📶 👍 💸'.split(' '),
'Post.html':'📮 ✉️ ✉️ 📮 💌 📦 📦 📤 📥 📍 🔢 🏷️ 🪟 📤 📥 ✍️'.split(' '),
'Berufe.html':'👨‍⚕️ 👩‍⚕️ 👨‍🏫 👩‍🏫 👨‍💼 👩‍💼 👨‍🍳 👩‍🍳 👨‍🔧 👩‍🔧 👨‍✈️ 👩‍✈️ 👮 👮‍♀️ 👨‍💻 👩‍💻'.split(' '),
'Buero.html':'🏢 🗄️ 🪑 💻 🖥️ ⌨️ 🖱️ 🖨️ 📄 🖊️ ✏️ 📁 📎 👥 👨‍💼 👩‍💼'.split(' '),
'Bewerbung.html':'📝 📄 ✉️ 📜 💼 🎓 💼 🧑‍🏫 🏢 🤝 🏢 🙋 🙋‍♀️ 📨 ✅ 💰'.split(' '),
'Amt.html':'🏛️ 🏛️ 🏛️ 📝 📝 🪪 🛂 📋 📋 📜 ✍️ 💍 🌍 ✍️ 📨 💶'.split(' '),
'Schule.html':'🏫 🎓 👨‍🎓 👩‍🎓 👨‍🎓 👩‍🎓 👨‍🏫 📖 👨‍🏫 🎤 👥 📝 📚 📖 🧠 🎓'.split(' '),
'Computer.html':'🖥️ 💻 🖥️ ⌨️ 🖱️ 📄 📁 ⚙️ 🌐 🌐 📶 🔒 📧 ⬇️ ⬆️ 💾'.split(' '),
'Handy.html':'📱 📱 ⚙️ 🖥️ 🔋 🔌 💬 📞 👤 📷 🎥 📞 💬 📷 📤 🔌'.split(' '),
'Medien.html':'📚 📕 📖 📰 📖 📝 📢 📺 🎬 📺 📻 📻 🎙️ 🎵 📖 👀'.split(' '),
'Begruessung.html':'👋 🌅 👋 🌇 👋 👋 🙂 😊 🙏 🪪 🪪 🌍 🌍 🤝 🙇 👋'.split(' '),
'Familie.html':'👨‍👩‍👧‍👦 👨‍👩‍👧‍👦 👨 👩 👦 👧 👦 👧 🧑‍🤝‍🧑 👴 👵 👦 👧 👨 👩 💍'.split(' '),
'Gefuehle.html':'😊 😢 😄 😠 😴 😰 😌 😲 😨 🙂 🤝 🤲 🧘 💪 😄 ✅'.split(' '),
'Termin.html':'🕒 🕒 ⏱️ ⏱️ 📅 🗓️ 🗓️ 🗓️ 📅 🤝 📌 ➡️ ⬅️ 🌅 🌇 ⏰'.split(' '),
'Feste.html':'🎉 🗓️ 🎂 💒 🎄 🐣 🎆 🎆 🎭 🎁 💌 🎉 🥳 🎊 🎄 🥳'.split(' '),
'Wetter.html':'🌤️ ☀️ 🌧️ ❄️ 💨 ☁️ 🌫️ ⛈️ 🌡️ ☀️ ☁️ 🌧️ 🌷 🏖️ 🍂 ⛄'.split(' '),
'Tiere.html':'🐾 🐕 🐈 🐦 🐟 🐇 🐎 🐄 🐖 🐑 🐐 🐔 🦆 🦁 🐘 🦒'.split(' '),
'Zahlen.html':'0️⃣ 1️⃣ 2️⃣ 3️⃣ 🔟 💯 🔢 🔢 ⚖️ ➕ ➖ ➕ ➖ 🧩 ⚖️ 🥛'.split(' '),
'Farben.html':'🔴 🔵 🟡 🟢 ⚫ ⚪ 🌑 🟤 🟠 🌸 🟣 ⭕ 🟦 ▭ 🔺 🔷'.split(' ')
};
